/*
 * Copyright (C) 2012 Timo Vesalainen
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.vesalainen.bcc;

import java.io.DataInput;
import java.io.DataOutput;
import java.io.IOException;
import java.lang.annotation.Annotation;
import java.util.ArrayList;
import java.util.Collections;
import java.util.EnumSet;
import java.util.List;
import java.util.Set;
import javax.lang.model.element.AnnotationMirror;
import javax.lang.model.element.AnnotationValue;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.ElementVisitor;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.Name;
import javax.lang.model.element.TypeElement;
import javax.lang.model.element.TypeParameterElement;
import javax.lang.model.element.VariableElement;
import javax.lang.model.type.ExecutableType;
import javax.lang.model.type.TypeKind;
import javax.lang.model.type.TypeMirror;
import javax.lang.model.type.TypeVariable;
import javax.lang.model.type.TypeVisitor;
import org.vesalainen.annotation.dump.Descriptor;
import org.vesalainen.annotation.dump.Signature;
import org.vesalainen.bcc.annotation.ModelUtil;
import org.vesalainen.bcc.model.E;
import org.vesalainen.bcc.model.T;

/**
 *
 * @author tkv
 */
public class MethodInfo implements Writable, ExecutableElement
{
    /**
     * Declared public; may be accessed from outside its package.
     */
    public static final int ACC_PUBLIC = 0x0001;
    /**
     * Declared private; accessible only within the defining class.
     */
    public static final int ACC_PRIVATE = 0x0002;
    /**
     * Declared protected; may be accessed within subclasses.
     */
    public static final int ACC_PROTECTED = 0x0004;
    /**
     * Declared static.
     */
    public static final int ACC_STATIC = 0x0008;
    /**
     * Declared final; no subclasses allowed.
     */
    public static final int ACC_FINAL = 0x0010;
    /**
     * Declared synchronized; invocation is wrapped by a monitor use.
     */
    public static final int ACC_SYNCHRONIZED = 0x0020;
    /**
     * A bridge method, generated by the compiler
     */
    public static final int ACC_BRIDGE = 0x0040;
    /**
     * Declared with variable number of arguments.
     */
    public static final int ACC_VARARGS = 0x0080;
    /**
     * Declared native; implemented in a language other than Java
     */
    public static final int ACC_NATIVE = 0x0100;
    /**
     * Declared abstract; must not be instantiated.
     */
    public static final int ACC_ABSTRACT = 0x0400;
    /**
     * Declared strictfp; ﬂoating-point mode is FP-strict
     */
    public static final int ACC_STRICT = 0x0800;
    /**
     * Declared synthetic; Not present in the source code.
     */
    public static final int ACC_SYNTHETIC = 0x1000;

    private ExecutableElement executableElement;
    private ClassFile enclosingElement;
    private int name_index;
    private int descriptor_index;
    private List<AttributeInfo> attributes = new ArrayList<>();
    private MethodCompiler mc;
    private boolean bridge;
    private boolean varArgs;
    private boolean synthetic;
    private CodeAttribute code;
    /**
     * 
     * @param access_flags
     * @param name_index
     * @param descriptor_index
     */
    MethodInfo(ClassFile cf, ExecutableElement executableElement)
    {
        this.enclosingElement = cf;
        this.executableElement = executableElement;
        this.name_index = enclosingElement.getNameIndex(executableElement.getSimpleName());
        this.descriptor_index = enclosingElement.getNameIndex(Descriptor.getDesriptor(executableElement));
        code = new CodeAttribute(cf);
        attributes.add(code);
    }

    MethodInfo(ClassFile cf, DataInput in) throws IOException
    {
        this.enclosingElement = cf;
        int access_flags = in.readUnsignedShort();
        name_index = in.readUnsignedShort();
        descriptor_index = in.readUnsignedShort();
        int attributes_count = in.readUnsignedShort();
        for (int ii=0;ii<attributes_count;ii++)
        {
            attributes.add(AttributeInfo.getInstance(cf, in));
        }
    }

    public ExecutableElement getExecutableElement()
    {
        return executableElement;
    }

    private int addModifiers()
    {
        int flags = 0;
        if (bridge)
        {
            flags |= ACC_BRIDGE;
        }
        if (varArgs)
        {
            flags |= ACC_VARARGS;
        }
        if (synthetic)
        {
            flags |= ACC_SYNTHETIC;
        }
        for (Modifier m : getModifiers())
        {
            switch (m)
            {
                case ABSTRACT:
                    flags |= ACC_ABSTRACT;
                    break;
                case FINAL:
                    flags |= ACC_FINAL;
                    break;
                case NATIVE:
                    flags |= ACC_NATIVE;
                    break;
                case PRIVATE:
                    flags |= ACC_PRIVATE;
                    break;
                case PROTECTED:
                    flags |= ACC_PROTECTED;
                    break;
                case PUBLIC:
                    flags |= ACC_PUBLIC;
                    break;
                case STATIC:
                    flags |= ACC_STATIC;
                    break;
                case STRICTFP:
                    flags |= ACC_STRICT;
                    break;
                case SYNCHRONIZED:
                    flags |= ACC_SYNCHRONIZED;
                    break;
                default:
                    throw new IllegalArgumentException(m+" is not valid method flag");
            }
        }
        return flags;
    }
    public String getModifiersAsString()
    {
        StringBuilder sb = new StringBuilder();
        for (Modifier m : getModifiers())
        {
            sb.append(m);
            sb.append(' ');
        }
        if (bridge)
        {
            sb.append("bridge ");
        }
        if (varArgs)
        {
            sb.append("varagrs ");
        }
        if (synthetic)
        {
            sb.append("synthetic ");
        }
        return sb.toString();
    }
    private void addThrowables()
    {
        for (TypeMirror tt : getThrownTypes())
        {
            ExceptionsAttribute ea = null;
            for (AttributeInfo ai : attributes)
            {
                if (ai instanceof ExceptionsAttribute)
                {
                    ea = (ExceptionsAttribute) ai;
                    break;
                }
            }
            if (ea == null)
            {
                ea = new ExceptionsAttribute(enclosingElement);
                attributes.add(ea);
            }
            ea.addThrowable((TypeElement)T.asElement(tt));
        }
    }
    
    private void addSignatureIfNeed()
    {
        String signature = Signature.getSignature(this);
        if (!signature.isEmpty())
        {
            attributes.add(new SignatureAttribute(enclosingElement, signature));
        }
    }
    @Override
    public boolean isVarArgs()
    {
        return varArgs;
    }

    @Override
    public ClassFile getEnclosingElement()
    {
        return enclosingElement;
    }

    @Override
    public <R, P> R accept(ElementVisitor<R, P> v, P p)
    {
        return v.visitExecutable(this, p);
    }

    public String getDescriptor()
    {
        return enclosingElement.getString(descriptor_index);
    }
    public MethodCompiler getMc()
    {
        return mc;
    }

    public void setMc(MethodCompiler mc)
    {
        this.mc = mc;
    }

    public CodeAttribute getCodeAttribute()
    {
        for (AttributeInfo ai : attributes)
        {
            if (ai instanceof CodeAttribute)
            {
                return (CodeAttribute) ai;
            }
        }
        return null;
    }

    @Override
    public void write(DataOutput out) throws IOException
    {
        addSignatureIfNeed();
        addThrowables();
        out.writeShort(addModifiers());
        out.writeShort(name_index);
        out.writeShort(descriptor_index);
        out.writeShort(attributes.size());
        for (AttributeInfo ai : attributes)
        {
            ai.write(out);
        }
    }

    public int getDescriptor_index()
    {
        return descriptor_index;
    }

    public int getName_index()
    {
        return name_index;
    }

    private Set<Modifier> getModifiers(int access_flags)
    {
        Set<Modifier> modifiers = EnumSet.noneOf(Modifier.class);
        if ((access_flags & ACC_PUBLIC) != 0)
        {
            modifiers.add(Modifier.PUBLIC);
        }
        if ((access_flags & ACC_PRIVATE) != 0)
        {
            modifiers.add(Modifier.PRIVATE);
        }
        if ((access_flags & ACC_PROTECTED) != 0)
        {
            modifiers.add(Modifier.PROTECTED);
        }
        if ((access_flags & ACC_STATIC) != 0)
        {
            modifiers.add(Modifier.STATIC);
        }
        if ((access_flags & ACC_FINAL) != 0)
        {
            modifiers.add(Modifier.FINAL);
        }
        if ((access_flags & ACC_SYNCHRONIZED) != 0)
        {
            modifiers.add(Modifier.SYNCHRONIZED);
        }
        if ((access_flags & ACC_NATIVE) != 0)
        {
            modifiers.add(Modifier.NATIVE);
        }
        if ((access_flags & ACC_ABSTRACT) != 0)
        {
            modifiers.add(Modifier.ABSTRACT);
        }
        if ((access_flags & ACC_STRICT) != 0)
        {
            modifiers.add(Modifier.STRICTFP);
        }
        if ((access_flags & ACC_BRIDGE) != 0)
        {
            bridge = true;
        }
        if ((access_flags & ACC_VARARGS) != 0)
        {
            varArgs = true;
        }
        if ((access_flags & ACC_SYNTHETIC) != 0)
        {
            synthetic = true;
        }
        return modifiers;
    }

    @Override
    public Set<Modifier> getModifiers()
    {
        return executableElement.getModifiers();
    }

    @Override
    public List<? extends TypeMirror> getThrownTypes()
    {
        return executableElement.getThrownTypes();
    }

    @Override
    public List<? extends TypeParameterElement> getTypeParameters()
    {
        return executableElement.getTypeParameters();
    }

    @Override
    public TypeMirror getReturnType()
    {
        return executableElement.getReturnType();
    }

    @Override
    public List<? extends VariableElement> getParameters()
    {
        return executableElement.getParameters();
    }

    @Override
    public AnnotationValue getDefaultValue()
    {
        return executableElement.getDefaultValue();
    }

    @Override
    public Name getSimpleName()
    {
        return executableElement.getSimpleName();
    }

    @Override
    public TypeMirror asType()
    {
        return executableElement.asType();
    }

    @Override
    public ElementKind getKind()
    {
        return executableElement.getKind();
    }

    @Override
    public List<? extends AnnotationMirror> getAnnotationMirrors()
    {
        return executableElement.getAnnotationMirrors();
    }

    @Override
    public <A extends Annotation> A getAnnotation(Class<A> annotationType)
    {
        return executableElement.getAnnotation(annotationType);
    }

    @Override
    public List<? extends Element> getEnclosedElements()
    {
        return executableElement.getEnclosedElements();
    }

}
