/*
 * Copyright (C) 2012 Timo Vesalainen
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.vesalainen.bcc;

/**
 *
 * @author tkv
 */
public class OpCodeUtil implements OpCode
{
    public static String string(int opCode)
    {
        switch (opCode)
        {
            case NOP:
                return "nop";
            case ACONST_NULL:
                return "aconst_null";
            case ICONST_M1:
                return "iconst_m1";
            case ICONST_0:
                return "iconst_0";
            case ICONST_1:
                return "iconst_1";
            case ICONST_2:
                return "iconst_2";
            case ICONST_3:
                return "iconst_3";
            case ICONST_4:
                return "iconst_4";
            case ICONST_5:
                return "iconst_5";
            case LCONST_0:
                return "lconst_0";
            case LCONST_1:
                return "lconst_1";
            case FCONST_0:
                return "fconst_0";
            case FCONST_1:
                return "fconst_1";
            case FCONST_2:
                return "fconst_2";
            case DCONST_0:
                return "dconst_0";
            case DCONST_1:
                return "dconst_1";
            case BIPUSH:
                return "bipush";
            case SIPUSH:
                return "sipush";
            case LDC:
                return "ldc";
            case LDC_W:
                return "ldc_w";
            case LDC2_W:
                return "ldc2_w";
            case ILOAD:
                return "iload";
            case LLOAD:
                return "lload";
            case FLOAD:
                return "fload";
            case DLOAD:
                return "dload";
            case ALOAD:
                return "aload";
            case ILOAD_0:
                return "iload_0";
            case ILOAD_1:
                return "iload_1";
            case ILOAD_2:
                return "iload_2";
            case ILOAD_3:
                return "iload_3";
            case LLOAD_0:
                return "lload_0";
            case LLOAD_1:
                return "lload_1";
            case LLOAD_2:
                return "lload_2";
            case LLOAD_3:
                return "lload_3";
            case FLOAD_0:
                return "fload_0";
            case FLOAD_1:
                return "fload_1";
            case FLOAD_2:
                return "fload_2";
            case FLOAD_3:
                return "fload_3";
            case DLOAD_0:
                return "dload_0";
            case DLOAD_1:
                return "dload_1";
            case DLOAD_2:
                return "dload_2";
            case DLOAD_3:
                return "dload_3";
            case ALOAD_0:
                return "aload_0";
            case ALOAD_1:
                return "aload_1";
            case ALOAD_2:
                return "aload_2";
            case ALOAD_3:
                return "aload_3";
            case IALOAD:
                return "iaload";
            case LALOAD:
                return "laload";
            case FALOAD:
                return "faload";
            case DALOAD:
                return "daload";
            case AALOAD:
                return "aaload";
            case BALOAD:
                return "baload";
            case CALOAD:
                return "caload";
            case SALOAD:
                return "saload";
            case ISTORE:
                return "istore";
            case LSTORE:
                return "lstore";
            case FSTORE:
                return "fstore";
            case DSTORE:
                return "dstore";
            case ASTORE:
                return "astore";
            case ISTORE_0:
                return "istore_0";
            case ISTORE_1:
                return "istore_1";
            case ISTORE_2:
                return "istore_2";
            case ISTORE_3:
                return "istore_3";
            case LSTORE_0:
                return "lstore_0";
            case LSTORE_1:
                return "lstore_1";
            case LSTORE_2:
                return "lstore_2";
            case LSTORE_3:
                return "lstore_3";
            case FSTORE_0:
                return "fstore_0";
            case FSTORE_1:
                return "fstore_1";
            case FSTORE_2:
                return "fstore_2";
            case FSTORE_3:
                return "fstore_3";
            case DSTORE_0:
                return "dstore_0";
            case DSTORE_1:
                return "dstore_1";
            case DSTORE_2:
                return "dstore_2";
            case DSTORE_3:
                return "dstore_3";
            case ASTORE_0:
                return "astore_0";
            case ASTORE_1:
                return "astore_1";
            case ASTORE_2:
                return "astore_2";
            case ASTORE_3:
                return "astore_3";
            case IASTORE:
                return "iastore";
            case LASTORE:
                return "lastore";
            case FASTORE:
                return "fastore";
            case DASTORE:
                return "dastore";
            case AASTORE:
                return "aastore";
            case BASTORE:
                return "bastore";
            case CASTORE:
                return "castore";
            case SASTORE:
                return "sastore";
            case POP:
                return "pop";
            case POP2:
                return "pop2";
            case DUP:
                return "dup";
            case DUP_X1:
                return "dup_x1";
            case DUP_X2:
                return "dup_x2";
            case DUP2:
                return "dup2";
            case DUP2_X1:
                return "dup2_x1";
            case DUP2_X2:
                return "dup2_x2";
            case SWAP:
                return "swap";
            case IADD:
                return "iadd";
            case LADD:
                return "ladd";
            case FADD:
                return "fadd";
            case DADD:
                return "dadd";
            case ISUB:
                return "isub";
            case LSUB:
                return "lsub";
            case FSUB:
                return "fsub";
            case DSUB:
                return "dsub";
            case IMUL:
                return "imul";
            case LMUL:
                return "lmul";
            case FMUL:
                return "fmul";
            case DMUL:
                return "dmul";
            case IDIV:
                return "idiv";
            case LDIV:
                return "ldiv";
            case FDIV:
                return "fdiv";
            case DDIV:
                return "ddiv";
            case IREM:
                return "irem";
            case LREM:
                return "lrem";
            case FREM:
                return "frem";
            case LNEG:
                return "lneg";
            case FNEG:
                return "fneg";
            case DNEG:
                return "dneg";
            case ISHL:
                return "ishl";
            case LSHL:
                return "lshl";
            case ISHR:
                return "ishr";
            case LSHR:
                return "lshr";
            case IUSHR:
                return "iushr";
            case LUSHR:
                return "lushr";
            case IAND:
                return "iand";
            case LAND:
                return "land";
            case IOR:
                return "ior";
            case LOR:
                return "lor";
            case IXOR:
                return "ixor";
            case LXOR:
                return "lxor";
            case IINC:
                return "iinc";
            case I2L:
                return "i2l";
            case I2F:
                return "i2f";
            case I2D:
                return "i2d";
            case L2I:
                return "l2i";
            case L2F:
                return "l2f";
            case L2D:
                return "l2d";
            case F2I:
                return "f2i";
            case F2L:
                return "f2l";
            case F2D:
                return "f2d";
            case D2I:
                return "d2i";
            case D2L:
                return "d2l";
            case D2F:
                return "d2f";
            case I2B:
                return "i2b";
            case I2C:
                return "i2c";
            case I2S:
                return "i2s";
            case LCMP:
                return "lcmp";
            case FCMPL:
                return "fcmpl";
            case FCMPG:
                return "fcmpg";
            case DCMPL:
                return "dcmpl";
            case DCMPG:
                return "dcmpg";
            case IFEQ:
                return "ifeq";
            case IFNE:
                return "ifne";
            case IFLT:
                return "iflt";
            case IFGE:
                return "ifge";
            case IFGT:
                return "ifgt";
            case IFLE:
                return "ifle";
            case IF_ICMPEQ:
                return "if_icmpeq";
            case IF_ICMPNE:
                return "if_icmpne";
            case IF_ICMPLT:
                return "if_icmplt";
            case IF_ICMPGE:
                return "if_icmpge";
            case IF_ICMPGT:
                return "if_icmpgt";
            case IF_ICMPLE:
                return "if_icmple";
            case IF_ACMPEQ:
                return "if_acmpeq";
            case IF_ACMPNE:
                return "if_acmpne";
            case GOTO:
                return "goto ";
            case JSR:
                return "jsr";
            case RET:
                return "ret";
            case TABLESWITCH:
                return "tableswitch";
            case LOOKUPSWITCH:
                return "lookupswitch";
            case IRETURN:
                return "ireturn";
            case LRETURN:
                return "lreturn";
            case FRETURN:
                return "freturn";
            case DRETURN:
                return "dreturn";
            case ARETURN:
                return "areturn";
            case RETURN:
                return "return";
            case GETSTATIC:
                return "getstatic";
            case PUTSTATIC:
                return "putstatic";
            case GETFIELD:
                return "getfield";
            case PUTFIELD:
                return "putfield";
            case INVOKEVIRTUAL:
                return "invokevirtual";
            case INVOKESPECIAL:
                return "invokespecial";
            case INVOKESTATIC:
                return "invokestatic";
            case INVOKEINTERFACE:
                return "invokeinterface";
            case NEW:
                return "new";
            case NEWARRAY:
                return "newarray";
            case ANEWARRAY:
                return "anewarray";
            case ARRAYLENGTH:
                return "arraylength";
            case ATHROW:
                return "athrow";
            case CHECKCAST:
                return "checkcast";
            case INSTANCEOF:
                return "instanceof";
            case MONITORENTER:
                return "monitorenter";
            case MONITOREXIT:
                return "monitorexit";
            case WIDE:
                return "wide";
            case MULTIANEWARRAY:
                return "multianewarray";
            case IFNULL:
                return "ifnull";
            case IFNONNULL:
                return "ifnonnull";
            case GOTO_W:
                return "goto_w";
            case JSR_W:
                return "jsr_w";
            case BREAKPOINT:
                return "breakpoint";
            case IMPDEP1:
                return "impdep1";
            case IMPDEP2:
                return "impdep2";
            default:
                throw new IllegalArgumentException(opCode+" is not an opcode");
        }
    }
    /*
case NOP:
case ACONST_NULL:
case ICONST_M1:
case ICONST_0:
case ICONST_1:
case ICONST_2:
case ICONST_3:
case ICONST_4:
case ICONST_5:
case LCONST_0:
case LCONST_1:
case FCONST_0:
case FCONST_1:
case FCONST_2:
case DCONST_0:
case DCONST_1:
case BIPUSH:
case SIPUSH:
case LDC:
case LDC_W:
case LDC2_W:
case ILOAD:
case LLOAD:
case FLOAD:
case DLOAD:
case ALOAD:
case ILOAD_0:
case ILOAD_1:
case ILOAD_2:
case ILOAD_3:
case LLOAD_0:
case LLOAD_1:
case LLOAD_2:
case LLOAD_3:
case FLOAD_0:
case FLOAD_1:
case FLOAD_2:
case FLOAD_3:
case DLOAD_0:
case DLOAD_1:
case DLOAD_2:
case DLOAD_3:
case ALOAD_0:
case ALOAD_1:
case ALOAD_2:
case ALOAD_3:
case IALOAD:
case LALOAD:
case FALOAD:
case DALOAD:
case AALOAD:
case BALOAD:
case CALOAD:
case SALOAD:
case ISTORE:
case LSTORE:
case FSTORE:
case DSTORE:
case ASTORE:
case ISTORE_0:
case ISTORE_1:
case ISTORE_2:
case ISTORE_3:
case LSTORE_0:
case LSTORE_1:
case LSTORE_2:
case LSTORE_3:
case FSTORE_0:
case FSTORE_1:
case FSTORE_2:
case FSTORE_3:
case DSTORE_0:
case DSTORE_1:
case DSTORE_2:
case DSTORE_3:
case ASTORE_0:
case ASTORE_1:
case ASTORE_2:
case ASTORE_3:
case IASTORE:
case LASTORE:
case FASTORE:
case DASTORE:
case AASTORE:
case BASTORE:
case CASTORE:
case SASTORE:
case POP:
case POP2:
case DUP:
case DUP_X1:
case DUP_X2:
case DUP2:
case DUP2_X1:
case DUP2_X2:
case SWAP:
case IADD:
case LADD:
case FADD:
case DADD:
case ISUB:
case LSUB:
case FSUB:
case DSUB:
case IMUL:
case LMUL:
case FMUL:
case DMUL:
case IDIV:
case LDIV:
case FDIV:
case DDIV:
case IREM:
case LREM:
case FREM:
case LNEG:
case FNEG:
case DNEG:
case ISHL:
case LSHL:
case ISHR:
case LSHR:
case IUSHR:
case LUSHR:
case IAND:
case LAND:
case IOR:
case LOR:
case IXOR:
case LXOR:
case IINC:
case I2L:
case I2F:
case I2D:
case L2I:
case L2F:
case L2D:
case F2I:
case F2L:
case F2D:
case D2I:
case D2L:
case D2F:
case I2B:
case I2C:
case I2S:
case LCMP:
case FCMPL:
case FCMPG:
case DCMPL:
case DCMPG:
case IFEQ:
case IFNE:
case IFLT:
case IFGE:
case IFGT:
case IFLE:
case IF_ICMPEQ:
case IF_ICMPNE:
case IF_ICMPLT:
case IF_ICMPGE:
case IF_ICMPGT:
case IF_ICMPLE:
case IF_ACMPEQ:
case IF_ACMPNE:
case GOTO :
case JSR:
case RET:
case TABLESWITCH:
case LOOKUPSWITCH:
case IRETURN:
case LRETURN:
case FRETURN:
case DRETURN:
case ARETURN:
case RETURN:
case GETSTATIC:
case PUTSTATIC:
case GETFIELD:
case PUTFIELD:
case INVOKEVIRTUAL:
case INVOKESPECIAL:
case INVOKESTATIC:
case INVOKEINTERFACE:
case NEW:
case NEWARRAY:
case ANEWARRAY:
case ARRAYLENGTH:
case ATHROW:
case CHECKCAST:
case INSTANCEOF:
case MONITORENTER:
case MONITOREXIT:
case WIDE:
case MULTIANEWARRAY:
case IFNULL:
case IFNONNULL:
case GOTO_W:
case JSR_W:
case BREAKPOINT:
case IMPDEP1:
case IMPDEP2:
     */
}
